-- Persistent catalogue, supplier, messaging and social-publication schema.
-- Every object is guarded so this can be applied to an existing project.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null default '',
  phone text not null default '',
  email text not null default '',
  city text not null default '',
  brand_name text not null default '',
  bank_name text,
  rib_number text,
  payment_method text,
  role text not null default 'affiliate',
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.suppliers (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null default '',
  email text not null default '',
  address text not null default '',
  city text not null default '',
  category text not null default '',
  notes text not null default '',
  products jsonb not null default '[]'::jsonb,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  key text not null unique,
  label_fr text not null,
  label_ar text not null default '',
  icon text not null default '📦',
  active boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.delivery_agencies (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null default '',
  email text not null default '',
  wilayas_covered jsonb not null default '[]'::jsonb,
  price_per_kg numeric(10, 2) not null default 0,
  delivery_delay text not null default '',
  tracking_url text not null default '',
  notes text not null default '',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  name text not null,
  category text not null default '',
  image_url text not null default '',
  wholesale_price numeric(10, 2) not null default 0,
  suggested_price numeric(10, 2) not null default 0,
  affiliate_margin numeric(10, 2) not null default 0,
  description text not null default '',
  delivery_cost numeric(10, 2) not null default 0,
  in_stock boolean not null default true,
  supplier_id bigint references public.suppliers(id) on delete set null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.product_media (
  id bigint generated by default as identity primary key,
  product_id bigint not null references public.products(id) on delete cascade,
  public_url text,
  storage_path text,
  alt_text text not null default '',
  sort_order integer not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.telegram_messages (
  id uuid primary key default gen_random_uuid(),
  telegram_message_id text,
  supplier_id bigint references public.suppliers(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  status text not null default 'received',
  error text,
  received_at timestamptz not null default now(),
  processed_at timestamptz
);

create table if not exists public.social_publications (
  id uuid primary key default gen_random_uuid(),
  product_id bigint references public.products(id) on delete set null,
  platform text not null,
  destination text,
  content text not null default '',
  status text not null default 'draft',
  external_post_id text,
  scheduled_at timestamptz,
  published_at timestamptz,
  error text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Add the fields required by the API when these tables predate this migration.
alter table if exists public.profiles add column if not exists role text not null default 'affiliate';
alter table if exists public.profiles add column if not exists status text not null default 'active';
alter table if exists public.profiles add column if not exists created_at timestamptz not null default now();
alter table if exists public.profiles add column if not exists updated_at timestamptz not null default now();

alter table if exists public.products add column if not exists supplier_id bigint;
alter table if exists public.products add column if not exists active boolean not null default true;
alter table if exists public.products add column if not exists created_at timestamptz not null default now();
alter table if exists public.products add column if not exists updated_at timestamptz not null default now();

alter table if exists public.orders add column if not exists user_id uuid references auth.users(id) on delete restrict;
alter table if exists public.withdrawals add column if not exists user_id uuid references auth.users(id) on delete restrict;

create index if not exists products_supplier_id_idx on public.products(supplier_id);
create index if not exists product_media_product_id_idx on public.product_media(product_id);
create index if not exists telegram_messages_supplier_id_idx on public.telegram_messages(supplier_id);
create index if not exists social_publications_product_id_idx on public.social_publications(product_id);
create index if not exists social_publications_status_idx on public.social_publications(status);

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and role = 'admin'
  );
$$;

revoke all on function public.is_admin() from public, anon, authenticated;

alter table public.profiles enable row level security;
alter table public.suppliers enable row level security;
alter table public.categories enable row level security;
alter table public.delivery_agencies enable row level security;
alter table public.products enable row level security;
alter table public.product_media enable row level security;
alter table public.telegram_messages enable row level security;
alter table public.social_publications enable row level security;
alter table public.orders enable row level security;
alter table public.withdrawals enable row level security;

drop policy if exists profiles_owner_or_admin on public.profiles;
create policy profiles_owner_or_admin on public.profiles
  for all to authenticated
  using (auth.uid() = id or public.is_admin())
  with check (auth.uid() = id or public.is_admin());

do $$
declare
  table_name text;
begin
  foreach table_name in array array[
    'suppliers', 'categories', 'delivery_agencies', 'products',
    'product_media', 'telegram_messages', 'social_publications'
  ] loop
    execute format('drop policy if exists %I on public.%I', table_name || '_authenticated_read', table_name);
    execute format(
      'create policy %I on public.%I for select to authenticated using (true)',
      table_name || '_authenticated_read', table_name
    );
    execute format('drop policy if exists %I on public.%I', table_name || '_admin_write', table_name);
    execute format(
      'create policy %I on public.%I for all to authenticated using (public.is_admin()) with check (public.is_admin())',
      table_name || '_admin_write', table_name
    );
  end loop;
end $$;

drop policy if exists orders_owner_or_admin on public.orders;
create policy orders_owner_or_admin on public.orders
  for all to authenticated
  using (auth.uid() = user_id or public.is_admin())
  with check (auth.uid() = user_id or public.is_admin());

drop policy if exists withdrawals_owner_or_admin on public.withdrawals;
create policy withdrawals_owner_or_admin on public.withdrawals
  for all to authenticated
  using (auth.uid() = user_id or public.is_admin())
  with check (auth.uid() = user_id or public.is_admin());